"""Command-line entry point for the trading crowding momentum strategy pipeline."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from src.backtest import run_all_backtests
from src.data_loader import download_panel
from src.factors import add_factors
from src.performance import annual_return_by_year, monthly_return, summarize_performance
from src.plotting import make_all_plots
from src.utils import ensure_directories, load_config, setup_logging


def _write_report(config: dict, summary: pd.DataFrame, failures_path: Path | None = None) -> None:
    """Write a compact Markdown backtest report."""
    report_path = Path(config["outputs"]["reports_dir"]) / "backtest_report.md"
    lines = [
        "# Backtest Report",
        "",
        "This report is generated by `python run_pipeline.py --config config.yaml`.",
        "",
        "## Performance Summary",
        "",
        summary.to_markdown(index=False),
        "",
        "## Data Diagnostics",
        "",
    ]
    if failures_path and failures_path.exists():
        lines.append(f"Some symbols failed to download. See `{failures_path.as_posix()}` and `outputs/reports/pipeline.log`.")
    else:
        lines.append("No provider-level data failures were recorded.")
    lines.extend(
        [
            "",
            "## Generated Figures",
            "",
            "- `outputs/figures/nav_comparison.png`",
            "- `outputs/figures/drawdown.png`",
            "- `outputs/figures/yearly_returns.png`",
            "- `outputs/figures/monthly_return_heatmap.png`",
            "- `outputs/figures/holding_count.png`",
            "- `outputs/figures/turnover.png`",
            "- `outputs/figures/factor_ic.png` when enough cross-sectional observations exist",
        ]
    )
    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    """Run the full data, factor, backtest, analytics, plotting, and report pipeline."""
    parser = argparse.ArgumentParser(description="Trading crowding momentum strategy research pipeline.")
    parser.add_argument("--config", default="config.yaml", help="Path to YAML config.")
    args = parser.parse_args()

    config = load_config(args.config)
    ensure_directories(config)
    logger = setup_logging(Path(config["outputs"]["reports_dir"]) / "pipeline.log")
    logger.info("Starting pipeline.")

    panel = download_panel(config, logger)
    factors = add_factors(panel, config)
    factor_path = Path(config["outputs"]["tables_dir"]) / "factor_values.csv"
    factors.to_csv(factor_path, index=False, encoding="utf-8-sig")
    logger.info("Saved factor values to %s.", factor_path)

    nav, weights, turnover = run_all_backtests(factors, config)
    nav_path = Path(config["outputs"]["tables_dir"]) / "portfolio_nav.csv"
    weights_path = Path(config["outputs"]["tables_dir"]) / "weekly_weights.csv"
    turnover_path = Path(config["outputs"]["tables_dir"]) / "turnover.csv"
    nav.to_csv(nav_path, index=False, encoding="utf-8-sig")
    weights.to_csv(weights_path, index=False, encoding="utf-8-sig")
    turnover.to_csv(turnover_path, index=False, encoding="utf-8-sig")
    logger.info("Saved backtest tables.")

    summary = summarize_performance(nav, turnover)
    monthly = monthly_return(nav)
    yearly = annual_return_by_year(nav)
    summary.to_csv(Path(config["outputs"]["tables_dir"]) / "performance_summary.csv", index=False, encoding="utf-8-sig")
    monthly.to_csv(Path(config["outputs"]["tables_dir"]) / "monthly_returns.csv", index=False, encoding="utf-8-sig")
    yearly.to_csv(Path(config["outputs"]["tables_dir"]) / "yearly_returns.csv", index=False, encoding="utf-8-sig")
    logger.info("Saved performance tables.")

    ic = make_all_plots(nav, weights, turnover, factors, monthly, yearly, config)
    if not ic.empty:
        ic.to_csv(Path(config["outputs"]["tables_dir"]) / "factor_ic.csv", index=False, encoding="utf-8-sig")
    failures_path = Path(config["outputs"]["reports_dir"]) / "data_failures.csv"
    _write_report(config, summary, failures_path if failures_path.exists() else None)
    logger.info("Pipeline finished successfully.")


if __name__ == "__main__":
    main()
