"""Command-line entry point for the trading crowding momentum strategy pipeline."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from src.backtest import run_all_backtests
from src.data_loader import download_panel
from src.factors import add_factors
from src.performance import annual_return_by_year, monthly_return, summarize_performance, summarize_period_performance
from src.plotting import make_all_plots
from src.strategy_metadata import strategy_label
from src.utils import ensure_directories, load_config, setup_logging


def _write_report(
    config: dict,
    summary: pd.DataFrame,
    nav: pd.DataFrame,
    turnover: pd.DataFrame,
    failures_path: Path | None = None,
) -> None:
    """Write a compact Markdown backtest report."""
    report_path = Path(config["outputs"]["reports_dir"]) / "backtest_report.md"
    primary = config["strategy"].get("primary_strategy", "momentum_crowding_convex")
    risk_free_rate = float(config.get("performance", {}).get("risk_free_rate", 0.0))
    split_date = pd.Timestamp(config.get("performance", {}).get("validation_split_date", "2023-01-01"))
    display_summary = summary.copy()
    display_summary["strategy"] = display_summary["strategy"].map(strategy_label)
    display_columns = [
        "strategy",
        "annual_return",
        "annual_volatility",
        "sharpe",
        "max_drawdown",
        "average_turnover",
        "final_nav",
    ]
    train = summarize_period_performance(
        nav,
        turnover,
        end=split_date - pd.Timedelta(days=1),
        risk_free_rate=risk_free_rate,
    )
    holdout = summarize_period_performance(
        nav,
        turnover,
        start=split_date,
        risk_free_rate=risk_free_rate,
    )
    validation_rows = []
    for label, frame in [("2018-2022 parameter-selection period", train), ("2023+ temporal holdout", holdout)]:
        selected = frame[frame["strategy"] == primary]
        if not selected.empty:
            row = selected.iloc[0]
            validation_rows.append(
                {
                    "period": label,
                    "annual_return": row["annual_return"],
                    "annual_volatility": row["annual_volatility"],
                    "sharpe": row["sharpe"],
                    "max_drawdown": row["max_drawdown"],
                }
            )
    validation = pd.DataFrame(validation_rows)
    optimizer_config = config["strategy"].get("convex_optimizer", {})
    lines = [
        "# Backtest Report",
        "",
        "This report is generated by `python run_pipeline.py --config config.yaml`.",
        "",
        f"Primary strategy: **{strategy_label(primary)}** (`{primary}`).",
        "",
        "Sharpe uses annualized arithmetic daily excess returns: "
        f"`sqrt(252) * mean(r - rf_daily) / std(r)`, with annual risk-free rate {risk_free_rate:.2%}.",
        "",
        "## Performance Summary",
        "",
        display_summary[display_columns].to_markdown(index=False),
        "",
        "## Temporal Validation",
        "",
        validation.to_markdown(index=False) if not validation.empty else "No temporal validation rows were available.",
        "",
        "These are historical backtests, not a guarantee that Sharpe will remain above 1 in every market regime.",
        "",
        "## Convex Optimizer Defaults",
        "",
        f"- Maximum ETF weight: {float(optimizer_config.get('max_weight', config['strategy']['max_weight'])):.0%}",
        f"- Covariance window / shrinkage: {int(optimizer_config.get('covariance_window', 120))} days / {float(optimizer_config.get('covariance_shrinkage', 0.1)):.0%}",
        f"- Risk aversion: {float(optimizer_config.get('risk_aversion', 4.0)):g}",
        f"- L1 turnover regularization: {float(optimizer_config.get('turnover_penalty_bps', 0.0)):g} bp-equivalent (a regularizer, not realized trading cost)",
        f"- Realized transaction-cost assumption: {float(config['strategy']['transaction_cost_bps']):g} bps one-way",
        "",
        "## Data Diagnostics",
        "",
    ]
    if failures_path and failures_path.exists():
        lines.append(f"Some symbols failed to download. See `{failures_path.as_posix()}` and `outputs/reports/pipeline.log`.")
    else:
        lines.append("No provider-level data failures were recorded.")
    lines.extend(
        [
            "",
            "## Generated Figures",
            "",
            "- `outputs/figures/nav_comparison.png`",
            "- `outputs/figures/drawdown.png`",
            "- `outputs/figures/yearly_returns.png`",
            "- `outputs/figures/monthly_return_heatmap.png`",
            "- `outputs/figures/holding_count.png`",
            "- `outputs/figures/turnover.png`",
            "- `outputs/figures/factor_ic.png` when enough cross-sectional observations exist",
        ]
    )
    report_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    """Run the full data, factor, backtest, analytics, plotting, and report pipeline."""
    parser = argparse.ArgumentParser(description="Trading crowding momentum strategy research pipeline.")
    parser.add_argument("--config", default="config.yaml", help="Path to YAML config.")
    args = parser.parse_args()

    config = load_config(args.config)
    ensure_directories(config)
    logger = setup_logging(Path(config["outputs"]["reports_dir"]) / "pipeline.log")
    logger.info("Starting pipeline.")

    panel = download_panel(config, logger)
    factors = add_factors(panel, config)
    factor_path = Path(config["outputs"]["tables_dir"]) / "factor_values.csv"
    factors.to_csv(factor_path, index=False, encoding="utf-8-sig")
    logger.info("Saved factor values to %s.", factor_path)

    nav, weights, turnover = run_all_backtests(factors, config)
    nav_path = Path(config["outputs"]["tables_dir"]) / "portfolio_nav.csv"
    weights_path = Path(config["outputs"]["tables_dir"]) / "weekly_weights.csv"
    turnover_path = Path(config["outputs"]["tables_dir"]) / "turnover.csv"
    nav.to_csv(nav_path, index=False, encoding="utf-8-sig")
    weights.to_csv(weights_path, index=False, encoding="utf-8-sig")
    turnover.to_csv(turnover_path, index=False, encoding="utf-8-sig")
    logger.info("Saved backtest tables.")

    summary = summarize_performance(
        nav,
        turnover,
        risk_free_rate=float(config.get("performance", {}).get("risk_free_rate", 0.0)),
    )
    monthly = monthly_return(nav)
    yearly = annual_return_by_year(nav)
    summary.to_csv(Path(config["outputs"]["tables_dir"]) / "performance_summary.csv", index=False, encoding="utf-8-sig")
    monthly.to_csv(Path(config["outputs"]["tables_dir"]) / "monthly_returns.csv", index=False, encoding="utf-8-sig")
    yearly.to_csv(Path(config["outputs"]["tables_dir"]) / "yearly_returns.csv", index=False, encoding="utf-8-sig")
    logger.info("Saved performance tables.")

    ic = make_all_plots(nav, weights, turnover, factors, monthly, yearly, config)
    if not ic.empty:
        ic.to_csv(Path(config["outputs"]["tables_dir"]) / "factor_ic.csv", index=False, encoding="utf-8-sig")
    failures_path = Path(config["outputs"]["reports_dir"]) / "data_failures.csv"
    _write_report(config, summary, nav, turnover, failures_path if failures_path.exists() else None)
    logger.info("Pipeline finished successfully.")


if __name__ == "__main__":
    main()
